
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from '@/components/theme-provider'
import { Dock, DockIcon } from "@/components/magicui/dock";
import { FaGithub, FaLinkedin, FaTwitter } from "react-icons/fa";
import { IoIosHome } from "react-icons/io";
import { IoMdPerson } from "react-icons/io";
import { GoCode } from "react-icons/go";
import { MdOutlineEmail } from "react-icons/md";
import { BiPencil } from "react-icons/bi";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Vedang Kanade | PortFolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="systemಸ

System: system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex flex-col min-h-screen">
            {/* Header */}
            <header></header>
            {/* Main content */}
            <main className="flex-1">{children}</main>
            {/* Sticky Dock */}
            <div className="fixed bottom-4 left-0 right-0 flex justify-center z-50">
              <Dock>
                <DockIcon>
                  <a href="/" >
                    <IoIosHome size={24} />
                  </a>
                </DockIcon>
                <DockIcon>
                  <a href="/about" >
                    <IoMdPerson size={24} />
                  </a>
                </DockIcon>
                <DockIcon>
                  <a href="/skills" >
                    <GoCode size={24} />
                  </a>
                </DockIcon>
                <DockIcon>
                  <a href="/contact" >
                    <MdOutlineEmail size={24} />
                  </a>
                </DockIcon>
                <DockIcon>
                  <a href="/projects" >
                    <BiPencil size={24} />
                  </a>
                </DockIcon>
                <DockIcon>
                  <a href="https://github.com/vedangkanade20" target="_blank" rel="noopener noreferrer">
                    <FaGithub size={24} />
                  </a>
                </DockIcon>
                <DockIcon>
                  <a href="https://www.linkedin.com/in/vedang-kanade-598a05276/" target="_blank" rel="noopener noreferrer">
                    <FaLinkedin size={24} />
                  </a>
                </DockIcon>
                <DockIcon>
                  <a href="https://x.com/VedangKanade" target="_blank" rel="noopener noreferrer">
                    <FaTwitter size={24} />
                  </a>
                </DockIcon>
              </Dock>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );